// Code generated by protoc-gen-go. DO NOT EDIT.
// source: control.proto

package controlpanel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthCode struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthCode) Reset()         { *m = AuthCode{} }
func (m *AuthCode) String() string { return proto.CompactTextString(m) }
func (*AuthCode) ProtoMessage()    {}
func (*AuthCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_1cbb2a8270886f94, []int{0}
}
func (m *AuthCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthCode.Unmarshal(m, b)
}
func (m *AuthCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthCode.Marshal(b, m, deterministic)
}
func (dst *AuthCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthCode.Merge(dst, src)
}
func (m *AuthCode) XXX_Size() int {
	return xxx_messageInfo_AuthCode.Size(m)
}
func (m *AuthCode) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthCode.DiscardUnknown(m)
}

var xxx_messageInfo_AuthCode proto.InternalMessageInfo

func (m *AuthCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type AppErrors struct {
	Error                []*ApplicationError `protobuf:"bytes,1,rep,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AppErrors) Reset()         { *m = AppErrors{} }
func (m *AppErrors) String() string { return proto.CompactTextString(m) }
func (*AppErrors) ProtoMessage()    {}
func (*AppErrors) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_1cbb2a8270886f94, []int{1}
}
func (m *AppErrors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppErrors.Unmarshal(m, b)
}
func (m *AppErrors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppErrors.Marshal(b, m, deterministic)
}
func (dst *AppErrors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppErrors.Merge(dst, src)
}
func (m *AppErrors) XXX_Size() int {
	return xxx_messageInfo_AppErrors.Size(m)
}
func (m *AppErrors) XXX_DiscardUnknown() {
	xxx_messageInfo_AppErrors.DiscardUnknown(m)
}

var xxx_messageInfo_AppErrors proto.InternalMessageInfo

func (m *AppErrors) GetError() []*ApplicationError {
	if m != nil {
		return m.Error
	}
	return nil
}

type ApplicationError struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Unix                 int64    `protobuf:"varint,2,opt,name=Unix,proto3" json:"Unix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationError) Reset()         { *m = ApplicationError{} }
func (m *ApplicationError) String() string { return proto.CompactTextString(m) }
func (*ApplicationError) ProtoMessage()    {}
func (*ApplicationError) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_1cbb2a8270886f94, []int{2}
}
func (m *ApplicationError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationError.Unmarshal(m, b)
}
func (m *ApplicationError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationError.Marshal(b, m, deterministic)
}
func (dst *ApplicationError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationError.Merge(dst, src)
}
func (m *ApplicationError) XXX_Size() int {
	return xxx_messageInfo_ApplicationError.Size(m)
}
func (m *ApplicationError) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationError.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationError proto.InternalMessageInfo

func (m *ApplicationError) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ApplicationError) GetUnix() int64 {
	if m != nil {
		return m.Unix
	}
	return 0
}

type SerializedData struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SerializedData) Reset()         { *m = SerializedData{} }
func (m *SerializedData) String() string { return proto.CompactTextString(m) }
func (*SerializedData) ProtoMessage()    {}
func (*SerializedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_1cbb2a8270886f94, []int{3}
}
func (m *SerializedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerializedData.Unmarshal(m, b)
}
func (m *SerializedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerializedData.Marshal(b, m, deterministic)
}
func (dst *SerializedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerializedData.Merge(dst, src)
}
func (m *SerializedData) XXX_Size() int {
	return xxx_messageInfo_SerializedData.Size(m)
}
func (m *SerializedData) XXX_DiscardUnknown() {
	xxx_messageInfo_SerializedData.DiscardUnknown(m)
}

var xxx_messageInfo_SerializedData proto.InternalMessageInfo

func (m *SerializedData) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type SetConfigParams struct {
	Auth                 *AuthCode       `protobuf:"bytes,1,opt,name=Auth,proto3" json:"Auth,omitempty"`
	Data                 *SerializedData `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SetConfigParams) Reset()         { *m = SetConfigParams{} }
func (m *SetConfigParams) String() string { return proto.CompactTextString(m) }
func (*SetConfigParams) ProtoMessage()    {}
func (*SetConfigParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_1cbb2a8270886f94, []int{4}
}
func (m *SetConfigParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigParams.Unmarshal(m, b)
}
func (m *SetConfigParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigParams.Marshal(b, m, deterministic)
}
func (dst *SetConfigParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigParams.Merge(dst, src)
}
func (m *SetConfigParams) XXX_Size() int {
	return xxx_messageInfo_SetConfigParams.Size(m)
}
func (m *SetConfigParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigParams.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigParams proto.InternalMessageInfo

func (m *SetConfigParams) GetAuth() *AuthCode {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *SetConfigParams) GetData() *SerializedData {
	if m != nil {
		return m.Data
	}
	return nil
}

type MessageList struct {
	Auth                 *AuthCode `protobuf:"bytes,1,opt,name=Auth,proto3" json:"Auth,omitempty"`
	Message              []string  `protobuf:"bytes,2,rep,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MessageList) Reset()         { *m = MessageList{} }
func (m *MessageList) String() string { return proto.CompactTextString(m) }
func (*MessageList) ProtoMessage()    {}
func (*MessageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_1cbb2a8270886f94, []int{5}
}
func (m *MessageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageList.Unmarshal(m, b)
}
func (m *MessageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageList.Marshal(b, m, deterministic)
}
func (dst *MessageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageList.Merge(dst, src)
}
func (m *MessageList) XXX_Size() int {
	return xxx_messageInfo_MessageList.Size(m)
}
func (m *MessageList) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageList.DiscardUnknown(m)
}

var xxx_messageInfo_MessageList proto.InternalMessageInfo

func (m *MessageList) GetAuth() *AuthCode {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *MessageList) GetMessage() []string {
	if m != nil {
		return m.Message
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_1cbb2a8270886f94, []int{6}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AuthCode)(nil), "controlpanel.AuthCode")
	proto.RegisterType((*AppErrors)(nil), "controlpanel.AppErrors")
	proto.RegisterType((*ApplicationError)(nil), "controlpanel.ApplicationError")
	proto.RegisterType((*SerializedData)(nil), "controlpanel.SerializedData")
	proto.RegisterType((*SetConfigParams)(nil), "controlpanel.SetConfigParams")
	proto.RegisterType((*MessageList)(nil), "controlpanel.MessageList")
	proto.RegisterType((*Empty)(nil), "controlpanel.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControllerClient interface {
	GetApplicationErrors(ctx context.Context, in *AuthCode, opts ...grpc.CallOption) (*AppErrors, error)
	SetConfig(ctx context.Context, in *SetConfigParams, opts ...grpc.CallOption) (*Empty, error)
	GetConfig(ctx context.Context, in *AuthCode, opts ...grpc.CallOption) (*SerializedData, error)
	GetDatabase(ctx context.Context, in *AuthCode, opts ...grpc.CallOption) (Controller_GetDatabaseClient, error)
	AddToDatabase(ctx context.Context, in *MessageList, opts ...grpc.CallOption) (*Empty, error)
	TriggerSendout(ctx context.Context, in *AuthCode, opts ...grpc.CallOption) (*Empty, error)
}

type controllerClient struct {
	cc *grpc.ClientConn
}

func NewControllerClient(cc *grpc.ClientConn) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) GetApplicationErrors(ctx context.Context, in *AuthCode, opts ...grpc.CallOption) (*AppErrors, error) {
	out := new(AppErrors)
	err := c.cc.Invoke(ctx, "/controlpanel.Controller/GetApplicationErrors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) SetConfig(ctx context.Context, in *SetConfigParams, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/controlpanel.Controller/SetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetConfig(ctx context.Context, in *AuthCode, opts ...grpc.CallOption) (*SerializedData, error) {
	out := new(SerializedData)
	err := c.cc.Invoke(ctx, "/controlpanel.Controller/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetDatabase(ctx context.Context, in *AuthCode, opts ...grpc.CallOption) (Controller_GetDatabaseClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Controller_serviceDesc.Streams[0], "/controlpanel.Controller/GetDatabase", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerGetDatabaseClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Controller_GetDatabaseClient interface {
	Recv() (*SerializedData, error)
	grpc.ClientStream
}

type controllerGetDatabaseClient struct {
	grpc.ClientStream
}

func (x *controllerGetDatabaseClient) Recv() (*SerializedData, error) {
	m := new(SerializedData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controllerClient) AddToDatabase(ctx context.Context, in *MessageList, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/controlpanel.Controller/AddToDatabase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) TriggerSendout(ctx context.Context, in *AuthCode, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/controlpanel.Controller/TriggerSendout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
type ControllerServer interface {
	GetApplicationErrors(context.Context, *AuthCode) (*AppErrors, error)
	SetConfig(context.Context, *SetConfigParams) (*Empty, error)
	GetConfig(context.Context, *AuthCode) (*SerializedData, error)
	GetDatabase(*AuthCode, Controller_GetDatabaseServer) error
	AddToDatabase(context.Context, *MessageList) (*Empty, error)
	TriggerSendout(context.Context, *AuthCode) (*Empty, error)
}

func RegisterControllerServer(s *grpc.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_GetApplicationErrors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetApplicationErrors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controlpanel.Controller/GetApplicationErrors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetApplicationErrors(ctx, req.(*AuthCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controlpanel.Controller/SetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).SetConfig(ctx, req.(*SetConfigParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controlpanel.Controller/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetConfig(ctx, req.(*AuthCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetDatabase_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AuthCode)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerServer).GetDatabase(m, &controllerGetDatabaseServer{stream})
}

type Controller_GetDatabaseServer interface {
	Send(*SerializedData) error
	grpc.ServerStream
}

type controllerGetDatabaseServer struct {
	grpc.ServerStream
}

func (x *controllerGetDatabaseServer) Send(m *SerializedData) error {
	return x.ServerStream.SendMsg(m)
}

func _Controller_AddToDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).AddToDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controlpanel.Controller/AddToDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).AddToDatabase(ctx, req.(*MessageList))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_TriggerSendout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).TriggerSendout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controlpanel.Controller/TriggerSendout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).TriggerSendout(ctx, req.(*AuthCode))
	}
	return interceptor(ctx, in, info, handler)
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "controlpanel.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetApplicationErrors",
			Handler:    _Controller_GetApplicationErrors_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _Controller_SetConfig_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _Controller_GetConfig_Handler,
		},
		{
			MethodName: "AddToDatabase",
			Handler:    _Controller_AddToDatabase_Handler,
		},
		{
			MethodName: "TriggerSendout",
			Handler:    _Controller_TriggerSendout_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDatabase",
			Handler:       _Controller_GetDatabase_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "control.proto",
}

func init() { proto.RegisterFile("control.proto", fileDescriptor_control_1cbb2a8270886f94) }

var fileDescriptor_control_1cbb2a8270886f94 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x5f, 0x6b, 0xe2, 0x40,
	0x10, 0x27, 0x46, 0xcf, 0xcb, 0x44, 0xbd, 0x63, 0x4f, 0xee, 0x72, 0x72, 0x27, 0x21, 0x4f, 0xc1,
	0x07, 0x91, 0xdc, 0x3d, 0xde, 0x21, 0x21, 0x95, 0xbc, 0xb4, 0x50, 0x12, 0xfb, 0x01, 0x56, 0xb3,
	0x4d, 0x17, 0xe2, 0x6e, 0xd8, 0xac, 0xd0, 0xf6, 0xd3, 0xf4, 0xa3, 0x96, 0xac, 0xd1, 0x9a, 0x54,
	0x0b, 0xed, 0x53, 0x66, 0xd8, 0xdf, 0xbf, 0x99, 0x21, 0xd0, 0x5f, 0x73, 0x26, 0x05, 0xcf, 0xa6,
	0xb9, 0xe0, 0x92, 0xa3, 0x5e, 0xd5, 0xe6, 0x98, 0x91, 0xcc, 0x19, 0xc3, 0x67, 0x7f, 0x2b, 0xef,
	0x02, 0x9e, 0x10, 0x84, 0xa0, 0x5d, 0x7e, 0x2d, 0xcd, 0xd6, 0x5c, 0x23, 0x52, 0xb5, 0xe3, 0x83,
	0xe1, 0xe7, 0xf9, 0x42, 0x08, 0x2e, 0x0a, 0xf4, 0x17, 0x3a, 0xaa, 0xb2, 0x34, 0x5b, 0x77, 0x4d,
	0x6f, 0x3c, 0x3d, 0x96, 0x9a, 0xfa, 0x79, 0x9e, 0xd1, 0x35, 0x96, 0x94, 0x33, 0x85, 0x8a, 0x76,
	0x60, 0xe7, 0x1f, 0x7c, 0x6d, 0x3e, 0xa1, 0xe1, 0x8b, 0x52, 0xe9, 0xb5, 0x6b, 0xca, 0x00, 0x37,
	0x8c, 0xde, 0x5b, 0x2d, 0x5b, 0x73, 0xf5, 0x48, 0xd5, 0xce, 0x04, 0x06, 0x31, 0x11, 0x14, 0x67,
	0xf4, 0x91, 0x24, 0x17, 0x58, 0x62, 0x64, 0x41, 0x37, 0xe0, 0x4c, 0x12, 0x26, 0x15, 0xbb, 0x17,
	0xed, 0x5b, 0x87, 0xc3, 0x97, 0x98, 0xc8, 0x80, 0xb3, 0x5b, 0x9a, 0x5e, 0x63, 0x81, 0x37, 0x05,
	0x9a, 0x40, 0xbb, 0x9c, 0x4f, 0x21, 0x4d, 0xef, 0x7b, 0x23, 0x71, 0x35, 0x79, 0xa4, 0x30, 0x68,
	0x06, 0xed, 0xd2, 0x40, 0xd9, 0x9b, 0xde, 0xaf, 0x3a, 0xb6, 0x1e, 0x22, 0x52, 0x48, 0x27, 0x06,
	0xf3, 0x8a, 0x14, 0x05, 0x4e, 0xc9, 0x25, 0x2d, 0xe4, 0xbb, 0xcc, 0x2c, 0xe8, 0x56, 0x54, 0xab,
	0x65, 0xeb, 0xae, 0x11, 0xed, 0x5b, 0xa7, 0x0b, 0x9d, 0xc5, 0x26, 0x97, 0x0f, 0xde, 0x93, 0x0e,
	0x10, 0xec, 0x24, 0x32, 0x22, 0x50, 0x08, 0xc3, 0x90, 0xc8, 0xe6, 0x2a, 0x0b, 0x74, 0xc6, 0x67,
	0xf4, 0xe3, 0xd5, 0x79, 0x2a, 0xc2, 0x1c, 0x8c, 0xc3, 0x9a, 0xd0, 0xef, 0xe6, 0x98, 0xb5, 0xfd,
	0x8d, 0xbe, 0xd5, 0x9f, 0x55, 0x30, 0xe4, 0x83, 0x11, 0x1e, 0x04, 0xce, 0xd9, 0xbf, 0xb9, 0x3f,
	0xb4, 0x00, 0x33, 0x24, 0xb2, 0x2c, 0x57, 0xb8, 0x20, 0x1f, 0x13, 0x99, 0x69, 0x68, 0x0e, 0x7d,
	0x3f, 0x49, 0x96, 0xfc, 0x20, 0xf4, 0xb3, 0x4e, 0x38, 0xba, 0xce, 0xe9, 0x51, 0xfe, 0xc3, 0x60,
	0x29, 0x68, 0x9a, 0x12, 0x11, 0x13, 0x96, 0xf0, 0xad, 0x3c, 0x1b, 0xe5, 0x14, 0x7d, 0xf5, 0x49,
	0xfd, 0x53, 0x7f, 0x9e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xda, 0x1f, 0x7a, 0x33, 0x64, 0x03, 0x00,
	0x00,
}
